
ACCESS_TOKEN = "1598566003-mFgBilmoj90zcF7Jo6YzexTazcOxewlPZnsmuOM"
ACCESS_TOKEN_SECRET = "qoUyg6n7ggV1npAikLAFe5jRjBFJ3d2E4Ni0RSdG1iTmw"
CONSUMER_KEY = "7jZ13gMkbLizza0gdkeQBwR8t"
CONSUMER_KEY_SECRET = "mc839sPwFhTnVfs0uwRJWpOsaJkOsjFJ3dsYuSz4ifLnLiKdWb"

def getKeys():
    return (ACCESS_TOKEN, ACCESS_TOKEN_SECRET, CONSUMER_KEY, CONSUMER_KEY_SECRET)
